name: build-test
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get dependencies
        run: npm install
      - name: type-check
        run: npm run type-check
      - name: unit-test
        run: npm run test:unit -- --run
      # playwright requires more initialization: https://playwright.dev/docs/ci-intro#on-pushpull_request
      # - name: e2e-test
      #   run: npm run test:e2e
      - name: build
        run: npm run build
